### ISSUE TITLE
Clips not working

### ISSUE THREAD

**Issue by ckorn** [mkoterle/twitchls#10]
When clicking on the Clip icon this site opens `https://clips.twitch.tv/clips` which just says `parameter 'segment' cannot be blank`.

**Comment by mkoterle** [comment]
Thanks for the report, will look into it asap.

**Comment by mkoterle** [comment]
Is it working now? I get redirected to the clips page without errors.

**Comment by ckorn** [comment]
Works, thanks.

**Comment by mkoterle** [comment]
I didn't do shit. It was on their end, they finally fixed it :)
