### ISSUE TITLE
Chat messages don't load when the URL has a case mismatch

### ISSUE THREAD

**Issue by TheIronBorn** [mkoterle/twitchls#11]
The stream and chat load fine, except that no chat messages ever appear.
- at `http://twitchls.com/nl_kripp` everything works normally:
  ![screen shot 2016-07-15 at 10 58 11 pm](https://cloud.githubusercontent.com/assets/7707250/16893168/6126f93a-4ae4-11e6-8b1d-cd6201e09daf.png)
- and at `http://twitchls.com/nl_kripP` no messages ever load:
  ![screen shot 2016-07-15 at 10 59 05 pm](https://cloud.githubusercontent.com/assets/7707250/16893172/69ece944-4ae4-11e6-8385-688d593a645d.png)
- Macbook Pro (13-inch, Early 2011)
- OS X `10.11.5`
- Chrome `52.0.2743.75` & `54.0.2798.0` & also the stable channel I believe
- BetterTTV `6.9` (with & w/out)

**Comment by mkoterle** [comment]
I tested this a bit and it seems that the chat rooms are case sensitive so you join an empty chat. It seems like no messages load but you are actually in a different chat room.

I think I can safely just transform the string to lowercase characters, so people who visit the page via a direct link with some capital letters, don't get thrown into a different chat room?

Does this sound ok?

**Comment by TheIronBorn** [comment]
Seems like a decent enough solution (as long as there's no uppercase channel names?).

**Comment by mkoterle** [comment]
I checked some popular streams and it seems like all chatrooms are lowercase even if their name has uppercase letters.

Will push a fix tomorrow.
