### ISSUE TITLE
Stream doesn't start in unfocused tab

### ISSUE THREAD

**Issue by kallebornemark** [mkoterle/twitchls#12]
Perhaps this is an issue related to HLS rather than twitchls, but when you start a stream without focusing the tab (e.g. with ctrl+click), the stream doesn't start.

**Comment by TheIronBorn** [comment]
I've found that to be the case as well and deal with it by reloading the video _frame_ rather than the whole page.
* At least in Chrome: right-click on the player UI and select `Reload Frame`.

**Comment by mkoterle** [comment]
Yea sadly I don't think I can do anything about this.

Does it happen on the twitch.tv website too? Streams don't load if the tab is not focused.

**Comment by TheIronBorn** [comment]
Seems that's the case.
- using Chrome with Flash disabled
