### ISSUE TITLE
Request: Add "list of followed games" and a button to go back to the followed channels while watching a stream

### ISSUE THREAD

**Issue by ST6Daniel** [mkoterle/twitchls#13]
So I noticed currently there is only "list of followed channels" available, not also list of followed games like on twitch.tv.

Also when watching a stream on twitchls.com the stream is fullscreen and there is no button to click on to go back to followed channels list, correct?

**Comment by mkoterle** [comment]
That is correct, there is no list of followed games. If I am understanding correctly you want a list of all streams with your currently followed games?

Currently you can go back using your favorite non back button clicking technique (finger swipe, mouse button 4, back keyboard button, etc.).

**Comment by ST6Daniel** [comment]
Yes correct! And I found another issue, there still seem to be links directing to Twitch.tv, for example while watching a stream and clicking on the name of the steamer we get redirected to twitch.tv website to view steamer profile. Also there is no way yet to view profile information in twitchls? (On twitch.tv you can scroll down and see all profile information below the steam window) :)
