### ISSUE TITLE
When invoking "https:..." there is specific error

### ISSUE THREAD

**Issue by ST6Daniel** [mkoterle/twitchls#14]
https://twitchls.com/

and you will get

Certificate expired Wednesday, 24. August 2016 22:29

code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by mkoterle** [comment]
There is no SSL on the site. It should automatically redirect you to http.

I had problems loading the twitch player & chat using ssl so I just turned it off. Maybe you are using https everywhere or some sort of similar browser addon?

**Comment by ST6Daniel** [comment]
No not using addon. Just normal Firefox 48.0.2.

Apparently it would work with one of these methods:

RewriteCond %{HTTPS} =on
RewriteRule ^(.*)$ http://%{HTTP_HOST}/$1 [L,R=301]

or

<If "%{HTTPS} == 'on'" >
Redirect permanent / http://production_server/
</If>


from here http://stackoverflow.com/questions/8371/how-do-you-redirect-https-to-http

Or these solutions for others

https://ca.godaddy.com/help/redirect-http-to-https-automatically-8828

But it says the server HAD a certificate, then I wonder why it is expired now? No new cert?

**Comment by mkoterle** [comment]
Thanks for the writeup. It's already setup in a similar way. But it seems that the certificate has to be valid in order for it to work. I renewed the certificate, it should be working again.
