### ISSUE TITLE
Hosting mode currently not working yet.

### ISSUE THREAD

**Issue by ST6Daniel** [mkoterle/twitchls#15]
Hey would be great to have host mode added soon! (When using "/host xyzchannelname " command)

**Comment by mkoterle** [comment]
Are you using this command while streaming? I am not familiar with it. The chat that loads is directly from twitch.tv

**Comment by ST6Daniel** [comment]
No I am not streaming, but another channel will be hosted via my stream.

**Comment by mkoterle** [comment]
Hmm, I am sorry, but I still don't understand the issue. Where do you input the /host command? What kind of response do you get? What kind of response do you want?

**Comment by ST6Daniel** [comment]
On your own channel chat (when stream offline) you can write " /host xyz" (channel that is currently streaming), then the other persons stream will be broadcasted on via your own channel! :)

**Comment by mkoterle** [comment]
This platform is mainly for viewers not streamers. So at this point streamer specific features will not be worked on.

**Comment by ST6Daniel** [comment]
alright! Also glad Twitch devs FIIIIINAALLY RELEASED the html5 player (or HLS? whatever its called) but LOL they STILL call it "beta" xD
