### ISSUE TITLE
VoD and replay chat support

### ISSUE THREAD

**Issue by North101** [mkoterle/twitchls#16]
So after fiddling about a bit, i figured out you can play html5 VoDs via http://player.twitch.tv/?video=<vod_id>&html5=true

e.g. https://www.twitch.tv/epicnamebro/v/89237339 becomes http://player.twitch.tv/?video=v89690585&html5=true

It would be great if you could add VoD support to the site along with replay chat.

**Comment by mkoterle** [comment]
It's on the roadmap.

Sadly I'm quite busy right now, so I'm not sure when :)
