### ISSUE TITLE
offline?

### ISSUE THREAD

**Issue by ST6Daniel** [mkoterle/twitchls#17]
Getting this when looking at my followed channels

"Oh snap! Something went wrong when connecting to the Twitch.tv Api. Please retry in a few seconds or try logging out and back in."

**Comment by mkoterle** [comment]
Just press the logout button on the top and login back again. It should work again. This happens every few weeks, can't reproduce it and sadly don't have the time to investigate it further.

**Comment by ST6Daniel** [comment]
alright! Probably a browser cache cookie issue with date outdated related to Twitch API or so...
