### ISSUE TITLE
An issue with "drag chat window wider"

### ISSUE THREAD

**Issue by XxBonf1r3xX** [mkoterle/twitchls#18]
Here's the deal, if you have BTTV installed and emote menu enabled and you're trying to click an emote on the emote menu near the "drag chat wider - line" it won't post an emote instead it will drag the chat window wider.

So my suggestion is that "drag chat window wider" line should be located somewhere else instead of in the middle of the chat window so the BTTV emote menu would not get messed up.

![untitled](https://cloud.githubusercontent.com/assets/22847583/19526819/5bb40da4-962e-11e6-9d6b-b946684e05cb.png)

**Comment by XxBonf1r3xX** [comment]
Ok, found a workaround. We can actually change how wide emote menu is, if the developer still wants to fix this issue I would be more than happy.

**Comment by mkoterle** [comment]
Yes, Ideally the sliding box would be smaller, I have some ideas how to fix that, but can't promise anything soon since I am swamped :)

Feel free to contribute tho!
