### ISSUE TITLE
View All Rooms text is cut off

### ISSUE THREAD

**Issue by wolfblake** [mkoterle/twitchls#2]
It is a very minor issue and I'm pretty sure not that many people switch chatrooms, but here it is anyway.

![bug](https://cloud.githubusercontent.com/assets/5151086/13573067/57abdba8-e443-11e5-8ce2-3bd5068dea80.png)

**Comment by mkoterle** [comment]
Thanks for the report. I am aware of this issue. I suspect this happens because the chat is in an iframe. I am not sure I can fix this tho. Will look into it.

**Comment by mkoterle** [comment]
Sadly there is no easy fix for this.
