### ISSUE TITLE
Fullscreen does not hide mouse cursor.

### ISSUE THREAD

**Issue by HDragonHR** [mkoterle/twitchls#21]
Browser : Firefox quantum 63.0.3
OS : Windows 10

Fullscreen mode hides the UI but not the mouse cursor.

**Comment by mkoterle** [comment]
Thanks for the report, I will check it in a couple of days as I get access to my Windows 10 machine.

Did this change? Is it a new problem?

**Comment by HDragonHR** [comment]
Just confirmed that this issue is related to Firefox. Tried your player on Edge and Chrome on Windows 10 and the cursor hides itself about the same time with the UI.

**Comment by mkoterle** [comment]
I've checked about this and it seems a Firefox problem, as nothing special has to be done to hide it. There are several issues reported to the Firefox issue tracker regarding this.

Is this a new issue for you?

**Comment by HDragonHR** [comment]
I think it is not a new issue. Because I never noticed that cursor ever behaving correctly. From first time I used your website I noticed the issue.

Since the issue is with Firefox then you can close this issue. Thanks for your time, mkoterle!
