### ISSUE TITLE
twitchls.com not working

### ISSUE THREAD

**Issue by cloc** [mkoterle/twitchls#24]
"Oh snap! Something went wrong when connecting to the Twitch.tv Api. Please retry in a few seconds."

Safari Version 13.0 (15608.2.2)

Edit: Working now

I’m not sure if reopening the issue is the correct way but the service has been down a couple of days now.

**Comment by mkoterle** [comment]
Twitch is phasing out their old API. I am aware of this, will try to fix it this weekend, sorry for the inconvenience if you know how, I am open to pull requests :)

**Comment by mkoterle** [comment]
Migrated to v5, it was easier than I thought, site is back online.

**Comment by cloc** [comment]
Well done! I use the site often and really appreciate it!
