### ISSUE TITLE
add redirect for www.twitchls.com and also for https 

### ISSUE THREAD

**Issue by mogoh** [mkoterle/twitchls#3]
Hello

Please add a redirect from www.twitchls.com to twitchls.com and from https to http.

Thanks

**Comment by mkoterle** [comment]
Currently the site is not available via https. Will change it soon.

**Comment by mkoterle** [comment]
Sadly the experimental HTML5 playback (used on Chrome/Firefox) is not working from https. The twitch.tv player tries to load from http and it fails. Until this is fixed https will not be used.
