### ISSUE TITLE
Game filter is not working for games with more than 1 word in the title.

### ISSUE THREAD

**Issue by 3154** [mkoterle/twitchls#6]
http://twitchls.com/

When I select a game from the dropdown above the streams list, if the game is more than 1 word (Dota 2, League of Legends) the resulting list is empty.

If I select a single word game (Overwatch, Minecraft) it works correctly.

**Comment by mkoterle** [comment]
Thanks for the report.

Already found the issue. On the production server I am using memcached which doesn't support spaces or control characters in keys, so this wasn't caught on the development server!

Will fix it soon.
