### ISSUE TITLE
30 secs of Purple Screen while watchin stream

### ISSUE THREAD

**Issue by ElBozz** [mkoterle/twitchls#74]
Twitch is showing this purple screen randomly while watching streaming, is less annoying than watching ads but still is kind of annoying.

please create a way to bypass this, regards.

![image](https://user-images.githubusercontent.com/99309839/200646332-86d1a14d-04b4-4e63-9cd2-06e2cfa7b07f.png)

**Comment by martink635** [comment]
This is out of the scope of this project, and not in my control. The site displays content directly from the embeded video.
