### ISSUE TITLE
When in fullscreen, the UI overlay remains longer

### ISSUE THREAD

**Issue by TheIronBorn** [mkoterle/twitchls#8]
- MacBook Pro (13-inch, Early 2011)
- OS X `10.11.5`
- Chrome `51.0.2704.106`

**Comment by mkoterle** [comment]
You mean there's a white background around the stream, when its supposed to be black?

It's really weird will look into it.

**Comment by mkoterle** [comment]
Do you still have this problem? It seems like it was a Twitch.tv issue, since I am not experiencing it anymore.

**Comment by TheIronBorn** [comment]
Still happening for me. 
Some clarification: the overlay seems to only disappear a few seconds after moving the cursor

**Comment by mkoterle** [comment]
I downgraded from Chrome Dev channel to Stable and I still can't reproduce this.

[Preview](http://d.pr/i/7PuX)

Can you try the usual: clean chrome cache/cookies or just try it in incognito mode.

**Comment by TheIronBorn** [comment]
I found this is also happening at twitch.tv proper so it seems an issue unrelated to twitchls.com.

Sorry for the inconvenience

**Comment by mkoterle** [comment]
Don't worry about it. 

I would try creating a new Chrome profile. Sometimes there are some weird issues regarding your profile.

**Comment by TheIronBorn** [comment]
Thanks
